# Generated by Django 5.0.6 on 2024-06-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnames',
            name='desciption',
            field=models.TextField(default=''),
        ),
    ]
