# Generated by Django 5.0.6 on 2024-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appnames_desciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnames',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
